### ISSUE TITLE
Mouse DATA :  "VALUE CHANGED" Always reports TRUE when working with DWHEEL MouseData

### ISSUE THREAD

**Issue by vuniverse** [thepgi/bge-logic-nodes-add-on#1]
I uploaded set up here.:
What i was trying to do is : Checking if mouse wheel moved and zoom camera according to it.
I used "If changed" as trigger but i could not have a result.
So I made a set up like this. Writing on the screen YES if CHANGED return TRUE and FALSE when it turns to FALSE.
Here i get TRUE report all the time cause it writes YES on to screen.

![wheel value changed](https://cloud.githubusercontent.com/assets/21278105/18027569/2696484a-6c70-11e6-94b4-6206dcf6b6fb.jpg)

**Comment by thepgi** [comment]
Checking. And this git thing works!

**Comment by thepgi** [comment]
Fixed in 0.2.8 (next version).
Either noone used that node before or I broke it in some update 'cause that thing was broken as broken can be.
