### ISSUE TITLE
Contact information.

### ISSUE THREAD

**Issue by vlad0337187** [thepgi/bge-logic-nodes-add-on#6]
Hello.
Sorry me for such "spam" message, but could you give me your contact information?
(maybe you're often in some IRC channel, e-mail, Facebook, something other - all will be good)

I want to write node "wrapper" over general logic bricks. Nodes will be very similar to appropriate logic bricks, but they may contain additional information: their position in window, their group.

This would give me speed of general logic bricks, written in C, and comfort of using nodes with groups, and flexibility of Python to edit it.

I would like to ask you: is it possible at all, if yes - then to ask you about literature, maybe some your notes and some advices. 
(I'm familiar with runtime Blender's API, but not with UI one, I even could not find in API reference)

Thank you.
Best regards,
Vladislav.

**Comment by thepgi** [comment]
Hello, my e-mail is pierluigi at tukano dot it.

**Comment by vlad0337187** [comment]
@thepgi , I wrote you a message, hope, you received it.

**Comment by vlad0337187** [comment]
@thepgi , you can close this issue.
I'll write when i'll have some questions.

Thank you.
